# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-15 18:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_auto_20170315_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='users',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submitters', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
